name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build:win
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exam-countdown-timer-installer.exe
          path: ./dist/exam-countdown-timer-1.0.0.exe
